### ISSUE TITLE
[BUG] ImproperlyConfigured exception when trying to run my population script

### ISSUE THREAD

**Issue by LewisDyer** [settlemysettle/SettleMySettle#13]
When I try performing
``` python populate_settle.py```

in `LD/population-script`, I receive the following error:
```
django.core.exceptions.ImproperlyConfigured: Requested setting DEFAULT_INDEX_TABLESPACE, but settings are not configured. You must either define the environment variable DJANGO_SETTINGS_MODULE or call settings.configure() before accessing settings.
```

I've double checked and I'm setting `DJANGO_SETTINGS_MODULE` from within my population script, but that doesn't seem to work. Can anyone else try running this on their machine and see whether it's an issue with my workspace?

**Comment by liamlau** [comment]
I get the same problem, so it's not an issue with your workspace unfortunately D: Will try stuff for a bit to try fix it

**Comment by liamlau** [comment]
Fixed: Just the order of the things before populate() was wrong - should be:

```import os
import django
os.environ.setdefault('DJANGO_SETTINGS_MODULE',
                      'settle_my_settle.settings')

django.setup()

from settle.models import Tag, User, Post, Comment```

My formatter automatically reordered these (cause it didn't like that the import statements weren't at the top) and it made it fail, so maybe that's what happened to you too :D

**Comment by LewisDyer** [comment]
That's great, thanks - my linter didn't like the import order either, but it seems importing models needs to come after django setup?
