### ISSUE TITLE
Can't add to ManyToMany fields on population script.

### ISSUE THREAD

**Issue by LewisDyer** [settlemysettle/SettleMySettle#15]
I'm trying to populate the Users, and most of the fields work fine, but the ManyToMany field (getting Tags) is annoying to populate. This is the method I'm using to add users:

```python
def add_user(username, password, favourite_games):
    user = User.objects.get_or_create(username=username, password=password)[0]
    user.save()
    for game in favourite_games:
        print(game["text"])
        user.favourite_games.add(Tag.objects.get(text=game["text"]))
    print(user.favourite_games)
    return(user)
```

And looking at the console I get the tag text correctly, but I don't get anything from the Tag model, so my users don't get any favourite games. Can someone take a look at this and see what the issue is? (I think it's something relatively obvious I'm just missing).

**Comment by LewisDyer** [comment]
(Also go ahead and commit something if you find a fix, I probably won't be able to work on it again until sometime tomorrow).

**Comment by liamlau** [comment]
I think the only problem was you were using `user.favourite_games`, but you should be using `user.favourite_games.all()` 😆 

The tags were getting added all along (I think)

**Comment by liamlau** [comment]
Took me a while to figure out though :/
